### ISSUE TITLE
Server exception

### ISSUE THREAD

**Issue by vspin** [b4rtaz/voice-assistant#8]
It would be great if the server code was available. It keeps crashing.

`6:16:45 PM Message received: activate from 127.0.0.1:56595
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Value does not fall within the expected range.
   at System.Speech.Internal.SapiInterop.ISpRecoResult.GetAlternates(Int32 ulStartElement, Int32 cElements, Int32 ulRequestCount, IntPtr[] ppPhrases, Int32& pcPhrasesReturned)
   at System.Speech.Recognition.RecognitionResult.ExtractDictationAlternates(ISpRecoResult recoResult, Int32 maxAlternates)
   at System.Speech.Recognition.RecognitionResult.Initialize(IRecognizerInternal recognizer, ISpRecoResult recoResult, Byte[] sapiResultBlob, Int32 maxAlternates)
   at System.Speech.Recognition.RecognizerBase.CreateRecognitionResult(SpeechEvent speechEvent)
   at System.Speech.Recognition.RecognizerBase.ProcessRecognitionEvent(SpeechEvent speechEvent)
   at System.Speech.Recognition.RecognizerBase.DispatchEvents(Object eventData)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Speech.Internal.AsyncSerializedWorker.WorkerProc(Object ignored)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by vspin** [comment]
It's available in author's repositories.
